services:
  toolkit-dev:
    build: .
    container_name: kc_toolkit_dev
    volumes:
      - .:/app
      - /app/node_modules  # 關鍵：防止宿主機的 node_modules 覆蓋容器內的
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true # 強化檔案變動監聽
    restart: unless-stopped
